## ??? ?????
# prod：生产   正式环境

spring:
  datasource:
#    type:com.mchange.v2.c3p0.ComboPooledDataSource
#    这里报错无所谓，因为会用服务器的mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.12.100:3306/crm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456

  ## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
  ## ?????
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  ## mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.msb.vo
  configuration:
    map-underscore-to-camel-case: true

  ## pageHelper
pagehelper:
  helper-dialect: mysql

  ## ?? dao ??????
logging:
  level:
    com:
      msb:
        mappers: debug